openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line descriiption
  version: 0.1.9

paths:
  /api/auth/register:
    post:
      summary: register user
      requestBody:
        required: true 
        content:
          application/json:
            schema:
              type: object
              required: 
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
                name: 
                  type: string
      responses:
        '200':
          description: User registered

  /api/auth/login:
    post:
      summary: login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged succesfully

  /api/auth/logout:
    post:
      summary: logout user
      responses:
        '200':
          description: User logged out succesfully

  /api/auth/me:
    get:
      summary: get current user
      responses:
        '200':
          description: current user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  name:
                    type: string
  


  /api/scenarios:
    get:
      summary: get scenario
      responses:
        '200':
          description: scenario
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    author_id:
                      type: string
                    public_id:
                      type: string
                    start_step_id:
                      type: string
    post:
      summary: create scenario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - status
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
      responses:
        '200':
          description: scenario created
          
  /api/scenarios/{scenarioId}:
    get:
      summary: Get scenario by id
      parameters:
        - name: scenarioId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Scenario data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  author_id:
                    type: string
                  status:
                    type: string
                  public_id:
                    type: string
                  start_step_id:
                    type: string

    patch:
      summary: Update scenario
      parameters:
        - name: scenarioId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
      responses:
        '200':
          description: Scenario updated

    delete:
      summary: Delete scenario
      parameters:
        - name: scenarioId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Scenario deleted

  

  /api/scenarios/{scenarioId}/steps:
    get:
      summary: Get steps of current scenario
      parameters:
        - name: scenarioId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of steps
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    scenario_id:
                      type: string
                    type:
                      type: string
                      enum: [start, text, choice, end]
                    content:
                      type: string
                    next_step_id:
                      type: string

    post:
      summary: Create step in current scenario
      parameters:
        - name: scenarioId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - type
                - content
              properties:
                type:
                  type: string
                  enum: [start, text, choice, end]
                content:
                  type: string
                next_step_id:
                  type: string
      responses:
        '200':
          description: Step created

  /api/steps/{stepId}:
    patch:
      summary: Update step
      parameters:
        - name: stepId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [start, text, choice, end]
                content:
                  type: string
                next_step_id:
                  type: string
      responses:
        '200':
          description: Step updated

    delete:
      summary: Delete step
      parameters:
        - name: stepId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Step deleted

  /api/steps/{stepId}/choices:
    get:
      summary: Get choices of current step
      parameters:
        - name: stepId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of choices
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    step_id:
                      type: string
                    text:
                      type: string
                    weight:
                      type: integer
                    next_step_id:
                      type: string

    post:
      summary: Create choice for step
      parameters:
        - name: stepId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
                weight:
                  type: integer
                next_step_id:
                  type: string
      responses:
        '200':
          description: Choice created

  /api/choices/{choiceId}:
    patch:
      summary: Update choice
      parameters:
        - name: choiceId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                weight:
                  type: integer
                next_step_id:
                  type: string
      responses:
        '200':
          description: Choice updated

    delete:
      summary: Delete choice
      parameters:
        - name: choiceId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Choice deletedscenarioId

  /api/scenarios/{scenarioId}/start-step:
    post:
      summary: set start step of scenario 
      parameters:
        - name: scenarioId
          in: path
          required: true 
          schema:
            type: string
      requiestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - step_id
              properties:
                step_id:
                  type: string
      responses:
        '200':
          description: Start step set succesfully            
